### ISSUE TITLE
Snapshot 213 out of bounds

### ISSUE THREAD

**Issue by madelinemarshall** [yqiuu/sector#4]
![screen shot 2018-05-29 at 11 59 30 am](https://user-images.githubusercontent.com/29718995/40634344-cb82da0c-6337-11e8-8052-938d7eb2b3b6.png)

Hi Yisheng,

When I try to run this down to snapshot 213 I get the above error. It works fine for snapshots <213. I've also attached the code I'm using. What do you think is wrong?

Cheers,
Maddie

![screen shot 2018-05-29 at 12 01 49 pm](https://user-images.githubusercontent.com/29718995/40634388-16dbb88e-6338-11e8-867c-9de081e93780.png)

**Comment by yqiuu** [comment]
Hi Maddie,

Thanks for raising this. Snapshots listed in ``snaplist.txt`` should start at 0.

Cheers,
Yisheng
