### ISSUE TITLE
f(a) and f(b) must have different signs

### ISSUE THREAD

**Issue by madelinemarshall** [yqiuu/sector#5]
Hey Yisheng,

When I try to get dust corrected magnitudes for my z=0 snapshot I get the error below (I've also attached my code). Any idea what could be going on? I wondered if something happens with the reddening code because it tries to redshift things but this is z=0.

Thanks,
Maddie

![screen shot 2018-06-08 at 2 27 24 pm](https://user-images.githubusercontent.com/29718995/41138960-172ebf50-6b28-11e8-9d32-2819e9f3e3cc.png)

![screen shot 2018-06-08 at 2 25 49 pm](https://user-images.githubusercontent.com/29718995/41138940-f5597d5c-6b27-11e8-971e-0fcc0d92b7d2.png)

**Comment by yqiuu** [comment]
The second argument of ``mc.reddening`` has to be rest-frame 1600 angstrom absolute magnitude. I am not sure why you use Y098 instead.
