### ISSUE TITLE
sed on ozSTAR

### ISSUE THREAD

**Issue by qyx268** [yqiuu/sector#6]
Hi Yisheng,
How do I set SED on ozSTAR?
sedPath = "/lustre/projects/p113_astro/yqiu/magcalc/input/STARBURST99-Salpeter-default"

Cheers,
Yuxiang

**Comment by yqiuu** [comment]
Hi Yuxiang

You can find them at ``/fred/oz013/yqiu/projects/spectra``. In the directory, `S99-Salpeter-0.001` only has metallicity Z = 0.001,  The metallicity range of `S99-Salpeter-full` is Z = 0.001 - Z = 0.040. The other two have nebular continuum emission.

Cheers,
Yisheng

**Comment by qyx268** [comment]
which one is best for calculating UVJ magnitudes?

**Comment by yqiuu** [comment]
You may use ``S99-Salpeter-neb-0.001`` for high-redshift galaxies.

**Comment by qyx268** [comment]
good for 3<z<4?

**Comment by yqiuu** [comment]
I think so. The main reason to use constant metallicity is that the model overestimated the metallicity.  However, the metallicity does have some impacts on galaxy colours.

**Comment by qyx268** [comment]
good. thanks! have you used the infrared band before? The previous results (Chuanwu's code) seems to overestimate the infrared luminosity...

**Comment by yqiuu** [comment]
Unfortunately, I never use that.
